import Foundation

/// The 99 Names of Allah (Asma ul-Husna). Sourced from the Aladhan API.
struct NameOfAllah: Identifiable, Hashable {
    let id: Int
    let arabic: String
    let transliteration: String
    let meaning: String
}

enum AsmaulHusna {
    static let all: [NameOfAllah] = [
        NameOfAllah(id: 1, arabic: "الرَّحْمَنُ", transliteration: "Ar Rahmaan", meaning: "The Beneficent"),
        NameOfAllah(id: 2, arabic: "الرَّحِيمُ", transliteration: "Ar Raheem", meaning: "The Merciful"),
        NameOfAllah(id: 3, arabic: "الْمَلِكُ", transliteration: "Al Malik", meaning: "The King / Eternal Lord"),
        NameOfAllah(id: 4, arabic: "الْقُدُّوسُ", transliteration: "Al Quddus", meaning: "The Purest"),
        NameOfAllah(id: 5, arabic: "السَّلاَمُ", transliteration: "As Salaam", meaning: "The Source of Peace"),
        NameOfAllah(id: 6, arabic: "الْمُؤْمِنُ", transliteration: "Al Mu'min", meaning: "The inspirer of faith"),
        NameOfAllah(id: 7, arabic: "الْمُهَيْمِنُ", transliteration: "Al Muhaymin", meaning: "The Guardian"),
        NameOfAllah(id: 8, arabic: "الْعَزِيزُ", transliteration: "Al Azeez", meaning: "The Precious / The Most Mighty"),
        NameOfAllah(id: 9, arabic: "الْجَبَّارُ", transliteration: "Al Jabbaar", meaning: "The Compeller"),
        NameOfAllah(id: 10, arabic: "الْمُتَكَبِّرُ", transliteration: "Al Mutakabbir", meaning: "The Greatest"),
        NameOfAllah(id: 11, arabic: "الْخَالِقُ", transliteration: "Al Khaaliq", meaning: "The Creator"),
        NameOfAllah(id: 12, arabic: "الْبَارِئُ", transliteration: "Al Baari", meaning: "The Maker of Order"),
        NameOfAllah(id: 13, arabic: "الْمُصَوِّرُ", transliteration: "Al Musawwir", meaning: "The Shaper of Beauty"),
        NameOfAllah(id: 14, arabic: "الْغَفَّارُ", transliteration: "Al Ghaffaar", meaning: "The Forgiving"),
        NameOfAllah(id: 15, arabic: "الْقَهَّارُ", transliteration: "Al Qahhaar", meaning: "The Subduer"),
        NameOfAllah(id: 16, arabic: "الْوَهَّابُ", transliteration: "Al Wahhaab", meaning: "The Giver of All"),
        NameOfAllah(id: 17, arabic: "الرَّزَّاقُ", transliteration: "Ar Razzaaq", meaning: "The Sustainer"),
        NameOfAllah(id: 18, arabic: "الْفَتَّاحُ", transliteration: "Al Fattaah", meaning: "The Opener"),
        NameOfAllah(id: 19, arabic: "اَلْعَلِيْمُ", transliteration: "Al 'Aleem", meaning: "The Knower of all"),
        NameOfAllah(id: 20, arabic: "الْقَابِضُ", transliteration: "Al Qaabid", meaning: "The Constrictor"),
        NameOfAllah(id: 21, arabic: "الْبَاسِطُ", transliteration: "Al Baasit", meaning: "The Reliever"),
        NameOfAllah(id: 22, arabic: "الْخَافِضُ", transliteration: "Al Khaafid", meaning: "The Abaser"),
        NameOfAllah(id: 23, arabic: "الرَّافِعُ", transliteration: "Ar Raafi'", meaning: "The Exalter"),
        NameOfAllah(id: 24, arabic: "الْمُعِزُّ", transliteration: "Al Mu'iz", meaning: "The Bestower of Honour"),
        NameOfAllah(id: 25, arabic: "المُذِلُّ", transliteration: "Al Mudhil", meaning: "The Humiliator"),
        NameOfAllah(id: 26, arabic: "السَّمِيعُ", transliteration: "As Samee'", meaning: "The Hearer of all"),
        NameOfAllah(id: 27, arabic: "الْبَصِيرُ", transliteration: "Al Baseer", meaning: "The Seer of all"),
        NameOfAllah(id: 28, arabic: "الْحَكَمُ", transliteration: "Al Hakam", meaning: "The Judge"),
        NameOfAllah(id: 29, arabic: "الْعَدْلُ", transliteration: "Al 'Adl", meaning: "The Just"),
        NameOfAllah(id: 30, arabic: "اللَّطِيفُ", transliteration: "Al Lateef", meaning: "The Subtle One"),
        NameOfAllah(id: 31, arabic: "الْخَبِيرُ", transliteration: "Al Khabeer", meaning: "The All Aware"),
        NameOfAllah(id: 32, arabic: "الْحَلِيمُ", transliteration: "Al Haleem", meaning: "The Forebearing"),
        NameOfAllah(id: 33, arabic: "الْعَظِيمُ", transliteration: "Al 'Azeem", meaning: "The Maginificent"),
        NameOfAllah(id: 34, arabic: "الْغَفُورُ", transliteration: "Al Ghafoor", meaning: "The Great Forgiver"),
        NameOfAllah(id: 35, arabic: "الشَّكُورُ", transliteration: "Ash Shakoor", meaning: "The Rewarder of Thankfulness"),
        NameOfAllah(id: 36, arabic: "الْعَلِيُّ", transliteration: "Al 'Aliyy", meaning: "The Highest"),
        NameOfAllah(id: 37, arabic: "الْكَبِيرُ", transliteration: "Al Kabeer", meaning: "The Greatest"),
        NameOfAllah(id: 38, arabic: "الْحَفِيظُ", transliteration: "Al Hafeez", meaning: "The Preserver"),
        NameOfAllah(id: 39, arabic: "المُقيِت", transliteration: "Al Muqeet", meaning: "The Nourisher"),
        NameOfAllah(id: 40, arabic: "الْحسِيبُ", transliteration: "Al Haseeb", meaning: "The Reckoner"),
        NameOfAllah(id: 41, arabic: "الْجَلِيلُ", transliteration: "Al Jaleel", meaning: "The Majestic"),
        NameOfAllah(id: 42, arabic: "الْكَرِيمُ", transliteration: "Al Kareem", meaning: "The Generous"),
        NameOfAllah(id: 43, arabic: "الرَّقِيبُ", transliteration: "Ar Raqeeb", meaning: "The Watchful One"),
        NameOfAllah(id: 44, arabic: "الْمُجِيبُ", transliteration: "Al Mujeeb", meaning: "The Responder to Prayer"),
        NameOfAllah(id: 45, arabic: "الْوَاسِعُ", transliteration: "Al Waasi'", meaning: "The All Comprehending"),
        NameOfAllah(id: 46, arabic: "الْحَكِيمُ", transliteration: "Al Hakeem", meaning: "The Perfectly Wise"),
        NameOfAllah(id: 47, arabic: "الْوَدُودُ", transliteration: "Al Wudood", meaning: "The Loving One"),
        NameOfAllah(id: 48, arabic: "الْمَجِيدُ", transliteration: "Al Majeed", meaning: "The Most Glorious One"),
        NameOfAllah(id: 49, arabic: "الْبَاعِثُ", transliteration: "Al Baa'ith", meaning: "The Resurrector"),
        NameOfAllah(id: 50, arabic: "الشَّهِيدُ", transliteration: "Ash Shaheed", meaning: "The Witness"),
        NameOfAllah(id: 51, arabic: "الْحَقُّ", transliteration: "Al Haqq", meaning: "The Truth"),
        NameOfAllah(id: 52, arabic: "الْوَكِيلُ", transliteration: "Al Wakeel", meaning: "The Trustee"),
        NameOfAllah(id: 53, arabic: "الْقَوِيُّ", transliteration: "Al Qawiyy", meaning: "The Possessor of all strength"),
        NameOfAllah(id: 54, arabic: "الْمَتِينُ", transliteration: "Al Mateen", meaning: "The Forceful"),
        NameOfAllah(id: 55, arabic: "الْوَلِيُّ", transliteration: "Al Waliyy", meaning: "The Protector"),
        NameOfAllah(id: 56, arabic: "الْحَمِيدُ", transliteration: "Al Hameed", meaning: "The Praised"),
        NameOfAllah(id: 57, arabic: "الْمُحْصِي", transliteration: "Al Muhsi", meaning: "The Appraiser"),
        NameOfAllah(id: 58, arabic: "الْمُبْدِئُ", transliteration: "Al Mubdi", meaning: "The Originator"),
        NameOfAllah(id: 59, arabic: "الْمُعِيدُ", transliteration: "Al Mu'eed", meaning: "The Restorer"),
        NameOfAllah(id: 60, arabic: "الْمُحْيِي", transliteration: "Al Muhiy", meaning: "The Giver of life"),
        NameOfAllah(id: 61, arabic: "اَلْمُمِيتُ", transliteration: "Al Mumeet", meaning: "The Taker of life"),
        NameOfAllah(id: 62, arabic: "الْحَيُّ", transliteration: "Al Haiyy", meaning: "The Ever Living"),
        NameOfAllah(id: 63, arabic: "الْقَيُّومُ", transliteration: "Al Qayyoom", meaning: "The Self Existing"),
        NameOfAllah(id: 64, arabic: "الْوَاجِدُ", transliteration: "Al Waajid", meaning: "The Finder"),
        NameOfAllah(id: 65, arabic: "الْمَاجِدُ", transliteration: "Al Maajid", meaning: "The Glorious"),
        NameOfAllah(id: 66, arabic: "الْواحِدُ", transliteration: "Al Waahid", meaning: "The Only One"),
        NameOfAllah(id: 67, arabic: "اَلاَحَدُ", transliteration: "Al Ahad", meaning: "The One"),
        NameOfAllah(id: 68, arabic: "الصَّمَدُ", transliteration: "As Samad", meaning: "The Supreme Provider"),
        NameOfAllah(id: 69, arabic: "الْقَادِرُ", transliteration: "Al Qaadir", meaning: "The Powerful"),
        NameOfAllah(id: 70, arabic: "الْمُقْتَدِرُ", transliteration: "Al Muqtadir", meaning: "The Creator of all power"),
        NameOfAllah(id: 71, arabic: "الْمُقَدِّمُ", transliteration: "Al Muqaddim", meaning: "The Expediter"),
        NameOfAllah(id: 72, arabic: "الْمُؤَخِّرُ", transliteration: "Al Mu’akhir", meaning: "The Delayer"),
        NameOfAllah(id: 73, arabic: "الأوَّلُ", transliteration: "Al Awwal", meaning: "The First"),
        NameOfAllah(id: 74, arabic: "الآخِرُ", transliteration: "Al Aakhir", meaning: "The Last"),
        NameOfAllah(id: 75, arabic: "الظَّاهِرُ", transliteration: "Az Zaahir", meaning: "The Manifest"),
        NameOfAllah(id: 76, arabic: "الْبَاطِنُ", transliteration: "Al Baatin", meaning: "The Hidden"),
        NameOfAllah(id: 77, arabic: "الْوَالِي", transliteration: "Al Waali", meaning: "The Governor"),
        NameOfAllah(id: 78, arabic: "الْمُتَعَالِي", transliteration: "Al Muta’ali", meaning: "The Supreme One"),
        NameOfAllah(id: 79, arabic: "الْبَرُّ", transliteration: "Al Barr", meaning: "The Doer of Good"),
        NameOfAllah(id: 80, arabic: "التَّوَابُ", transliteration: "At Tawwaab", meaning: "The Guide to Repentence"),
        NameOfAllah(id: 81, arabic: "الْمُنْتَقِمُ", transliteration: "Al Muntaqim", meaning: "The Avenger"),
        NameOfAllah(id: 82, arabic: "العَفُوُّ", transliteration: "Al Afuww", meaning: "The Forgiver"),
        NameOfAllah(id: 83, arabic: "الرَّؤُوفُ", transliteration: "Ar Ra’oof", meaning: "The Clement"),
        NameOfAllah(id: 84, arabic: "مَالِكُ الْمُلْكِ", transliteration: "Maalik Ul Mulk", meaning: "The Owner / Soverign of All"),
        NameOfAllah(id: 85, arabic: "ذُوالْجَلاَلِ وَالإكْرَامِ", transliteration: "Dhu Al Jalaali Wa Al Ikraam", meaning: "Possessor of Majesty and Bounty"),
        NameOfAllah(id: 86, arabic: "الْمُقْسِطُ", transliteration: "Al Muqsit", meaning: "The Equitable One"),
        NameOfAllah(id: 87, arabic: "الْجَامِعُ", transliteration: "Al Jaami'", meaning: "The Gatherer"),
        NameOfAllah(id: 88, arabic: "الْغَنِيُّ", transliteration: "Al Ghaniyy", meaning: "The Rich One"),
        NameOfAllah(id: 89, arabic: "الْمُغْنِي", transliteration: "Al Mughi", meaning: "The Enricher"),
        NameOfAllah(id: 90, arabic: "اَلْمَانِعُ", transliteration: "Al Maani'", meaning: "The Preventer of harm"),
        NameOfAllah(id: 91, arabic: "الضَّارَّ", transliteration: "Ad Daaarr", meaning: "The Creator of the harmful"),
        NameOfAllah(id: 92, arabic: "النَّافِعُ", transliteration: "An Naafi’", meaning: "The Bestower of Benefits"),
        NameOfAllah(id: 93, arabic: "النُّورُ", transliteration: "An Noor", meaning: "The Light"),
        NameOfAllah(id: 94, arabic: "الْهَادِي", transliteration: "Al Haadi", meaning: "The Guider"),
        NameOfAllah(id: 95, arabic: "الْبَدِيعُ", transliteration: "Al Badi'", meaning: "The Originator"),
        NameOfAllah(id: 96, arabic: "اَلْبَاقِي", transliteration: "Al Baaqi", meaning: "The Everlasting One"),
        NameOfAllah(id: 97, arabic: "الْوَارِثُ", transliteration: "Al Waarith", meaning: "The Inhertior"),
        NameOfAllah(id: 98, arabic: "الرَّشِيدُ", transliteration: "Ar Rasheed", meaning: "The Most Righteous Guide"),
        NameOfAllah(id: 99, arabic: "الصَّبُورُ", transliteration: "As Saboor", meaning: "The Patient One"),
    ]
}
