import Foundation

struct QuranChapter: Identifiable, Hashable {
    let number: Int
    let transliteratedName: String
    let englishName: String
    let verseCount: Int

    var id: Int { number }

    var displayName: String {
        "\(number). \(transliteratedName)"
    }

    var detailName: String {
        "\(transliteratedName) - \(englishName)"
    }

    static func chapter(number: Int) -> QuranChapter {
        all.first { $0.number == number } ?? QuranChapter(number: number, transliteratedName: "Surah \(number)", englishName: "Chapter \(number)", verseCount: 286)
    }

    static let all: [QuranChapter] = [
        QuranChapter(number: 1, transliteratedName: "Al-Fatihah", englishName: "The Opening", verseCount: 7),
        QuranChapter(number: 2, transliteratedName: "Al-Baqarah", englishName: "The Cow", verseCount: 286),
        QuranChapter(number: 3, transliteratedName: "Ali 'Imran", englishName: "Family of Imran", verseCount: 200),
        QuranChapter(number: 4, transliteratedName: "An-Nisa", englishName: "The Women", verseCount: 176),
        QuranChapter(number: 5, transliteratedName: "Al-Ma'idah", englishName: "The Table Spread", verseCount: 120),
        QuranChapter(number: 6, transliteratedName: "Al-An'am", englishName: "The Cattle", verseCount: 165),
        QuranChapter(number: 7, transliteratedName: "Al-A'raf", englishName: "The Heights", verseCount: 206),
        QuranChapter(number: 8, transliteratedName: "Al-Anfal", englishName: "The Spoils of War", verseCount: 75),
        QuranChapter(number: 9, transliteratedName: "At-Tawbah", englishName: "The Repentance", verseCount: 129),
        QuranChapter(number: 10, transliteratedName: "Yunus", englishName: "Jonah", verseCount: 109),
        QuranChapter(number: 11, transliteratedName: "Hud", englishName: "Hud", verseCount: 123),
        QuranChapter(number: 12, transliteratedName: "Yusuf", englishName: "Joseph", verseCount: 111),
        QuranChapter(number: 13, transliteratedName: "Ar-Ra'd", englishName: "The Thunder", verseCount: 43),
        QuranChapter(number: 14, transliteratedName: "Ibrahim", englishName: "Abraham", verseCount: 52),
        QuranChapter(number: 15, transliteratedName: "Al-Hijr", englishName: "The Rocky Tract", verseCount: 99),
        QuranChapter(number: 16, transliteratedName: "An-Nahl", englishName: "The Bee", verseCount: 128),
        QuranChapter(number: 17, transliteratedName: "Al-Isra", englishName: "The Night Journey", verseCount: 111),
        QuranChapter(number: 18, transliteratedName: "Al-Kahf", englishName: "The Cave", verseCount: 110),
        QuranChapter(number: 19, transliteratedName: "Maryam", englishName: "Mary", verseCount: 98),
        QuranChapter(number: 20, transliteratedName: "Taha", englishName: "Ta-Ha", verseCount: 135),
        QuranChapter(number: 21, transliteratedName: "Al-Anbya", englishName: "The Prophets", verseCount: 112),
        QuranChapter(number: 22, transliteratedName: "Al-Hajj", englishName: "The Pilgrimage", verseCount: 78),
        QuranChapter(number: 23, transliteratedName: "Al-Mu'minun", englishName: "The Believers", verseCount: 118),
        QuranChapter(number: 24, transliteratedName: "An-Nur", englishName: "The Light", verseCount: 64),
        QuranChapter(number: 25, transliteratedName: "Al-Furqan", englishName: "The Criterion", verseCount: 77),
        QuranChapter(number: 26, transliteratedName: "Ash-Shu'ara", englishName: "The Poets", verseCount: 227),
        QuranChapter(number: 27, transliteratedName: "An-Naml", englishName: "The Ant", verseCount: 93),
        QuranChapter(number: 28, transliteratedName: "Al-Qasas", englishName: "The Stories", verseCount: 88),
        QuranChapter(number: 29, transliteratedName: "Al-'Ankabut", englishName: "The Spider", verseCount: 69),
        QuranChapter(number: 30, transliteratedName: "Ar-Rum", englishName: "The Romans", verseCount: 60),
        QuranChapter(number: 31, transliteratedName: "Luqman", englishName: "Luqman", verseCount: 34),
        QuranChapter(number: 32, transliteratedName: "As-Sajdah", englishName: "The Prostration", verseCount: 30),
        QuranChapter(number: 33, transliteratedName: "Al-Ahzab", englishName: "The Combined Forces", verseCount: 73),
        QuranChapter(number: 34, transliteratedName: "Saba", englishName: "Sheba", verseCount: 54),
        QuranChapter(number: 35, transliteratedName: "Fatir", englishName: "Originator", verseCount: 45),
        QuranChapter(number: 36, transliteratedName: "Ya-Sin", englishName: "Ya Sin", verseCount: 83),
        QuranChapter(number: 37, transliteratedName: "As-Saffat", englishName: "Those Who Set the Ranks", verseCount: 182),
        QuranChapter(number: 38, transliteratedName: "Sad", englishName: "The Letter Sad", verseCount: 88),
        QuranChapter(number: 39, transliteratedName: "Az-Zumar", englishName: "The Groups", verseCount: 75),
        QuranChapter(number: 40, transliteratedName: "Ghafir", englishName: "The Forgiver", verseCount: 85),
        QuranChapter(number: 41, transliteratedName: "Fussilat", englishName: "Explained in Detail", verseCount: 54),
        QuranChapter(number: 42, transliteratedName: "Ash-Shuraa", englishName: "The Consultation", verseCount: 53),
        QuranChapter(number: 43, transliteratedName: "Az-Zukhruf", englishName: "The Ornaments of Gold", verseCount: 89),
        QuranChapter(number: 44, transliteratedName: "Ad-Dukhan", englishName: "The Smoke", verseCount: 59),
        QuranChapter(number: 45, transliteratedName: "Al-Jathiyah", englishName: "The Crouching", verseCount: 37),
        QuranChapter(number: 46, transliteratedName: "Al-Ahqaf", englishName: "The Wind-Curved Sandhills", verseCount: 35),
        QuranChapter(number: 47, transliteratedName: "Muhammad", englishName: "Muhammad", verseCount: 38),
        QuranChapter(number: 48, transliteratedName: "Al-Fath", englishName: "The Victory", verseCount: 29),
        QuranChapter(number: 49, transliteratedName: "Al-Hujurat", englishName: "The Rooms", verseCount: 18),
        QuranChapter(number: 50, transliteratedName: "Qaf", englishName: "The Letter Qaf", verseCount: 45),
        QuranChapter(number: 51, transliteratedName: "Adh-Dhariyat", englishName: "The Winnowing Winds", verseCount: 60),
        QuranChapter(number: 52, transliteratedName: "At-Tur", englishName: "The Mount", verseCount: 49),
        QuranChapter(number: 53, transliteratedName: "An-Najm", englishName: "The Star", verseCount: 62),
        QuranChapter(number: 54, transliteratedName: "Al-Qamar", englishName: "The Moon", verseCount: 55),
        QuranChapter(number: 55, transliteratedName: "Ar-Rahman", englishName: "The Beneficent", verseCount: 78),
        QuranChapter(number: 56, transliteratedName: "Al-Waqi'ah", englishName: "The Inevitable", verseCount: 96),
        QuranChapter(number: 57, transliteratedName: "Al-Hadid", englishName: "The Iron", verseCount: 29),
        QuranChapter(number: 58, transliteratedName: "Al-Mujadilah", englishName: "The Pleading Woman", verseCount: 22),
        QuranChapter(number: 59, transliteratedName: "Al-Hashr", englishName: "The Exile", verseCount: 24),
        QuranChapter(number: 60, transliteratedName: "Al-Mumtahanah", englishName: "She That Is to Be Examined", verseCount: 13),
        QuranChapter(number: 61, transliteratedName: "As-Saff", englishName: "The Ranks", verseCount: 14),
        QuranChapter(number: 62, transliteratedName: "Al-Jumu'ah", englishName: "Friday", verseCount: 11),
        QuranChapter(number: 63, transliteratedName: "Al-Munafiqun", englishName: "The Hypocrites", verseCount: 11),
        QuranChapter(number: 64, transliteratedName: "At-Taghabun", englishName: "Mutual Disillusion", verseCount: 18),
        QuranChapter(number: 65, transliteratedName: "At-Talaq", englishName: "Divorce", verseCount: 12),
        QuranChapter(number: 66, transliteratedName: "At-Tahrim", englishName: "The Prohibition", verseCount: 12),
        QuranChapter(number: 67, transliteratedName: "Al-Mulk", englishName: "The Sovereignty", verseCount: 30),
        QuranChapter(number: 68, transliteratedName: "Al-Qalam", englishName: "The Pen", verseCount: 52),
        QuranChapter(number: 69, transliteratedName: "Al-Haqqah", englishName: "The Reality", verseCount: 52),
        QuranChapter(number: 70, transliteratedName: "Al-Ma'arij", englishName: "The Ascending Stairways", verseCount: 44),
        QuranChapter(number: 71, transliteratedName: "Nuh", englishName: "Noah", verseCount: 28),
        QuranChapter(number: 72, transliteratedName: "Al-Jinn", englishName: "The Jinn", verseCount: 28),
        QuranChapter(number: 73, transliteratedName: "Al-Muzzammil", englishName: "The Enshrouded One", verseCount: 20),
        QuranChapter(number: 74, transliteratedName: "Al-Muddaththir", englishName: "The Cloaked One", verseCount: 56),
        QuranChapter(number: 75, transliteratedName: "Al-Qiyamah", englishName: "The Resurrection", verseCount: 40),
        QuranChapter(number: 76, transliteratedName: "Al-Insan", englishName: "Man", verseCount: 31),
        QuranChapter(number: 77, transliteratedName: "Al-Mursalat", englishName: "The Emissaries", verseCount: 50),
        QuranChapter(number: 78, transliteratedName: "An-Naba", englishName: "The Tidings", verseCount: 40),
        QuranChapter(number: 79, transliteratedName: "An-Nazi'at", englishName: "Those Who Drag Forth", verseCount: 46),
        QuranChapter(number: 80, transliteratedName: "'Abasa", englishName: "He Frowned", verseCount: 42),
        QuranChapter(number: 81, transliteratedName: "At-Takwir", englishName: "The Overthrowing", verseCount: 29),
        QuranChapter(number: 82, transliteratedName: "Al-Infitar", englishName: "The Cleaving", verseCount: 19),
        QuranChapter(number: 83, transliteratedName: "Al-Mutaffifin", englishName: "Defrauding", verseCount: 36),
        QuranChapter(number: 84, transliteratedName: "Al-Inshiqaq", englishName: "The Splitting Open", verseCount: 25),
        QuranChapter(number: 85, transliteratedName: "Al-Buruj", englishName: "The Mansions of the Stars", verseCount: 22),
        QuranChapter(number: 86, transliteratedName: "At-Tariq", englishName: "The Nightcomer", verseCount: 17),
        QuranChapter(number: 87, transliteratedName: "Al-A'la", englishName: "The Most High", verseCount: 19),
        QuranChapter(number: 88, transliteratedName: "Al-Ghashiyah", englishName: "The Overwhelming", verseCount: 26),
        QuranChapter(number: 89, transliteratedName: "Al-Fajr", englishName: "The Dawn", verseCount: 30),
        QuranChapter(number: 90, transliteratedName: "Al-Balad", englishName: "The City", verseCount: 20),
        QuranChapter(number: 91, transliteratedName: "Ash-Shams", englishName: "The Sun", verseCount: 15),
        QuranChapter(number: 92, transliteratedName: "Al-Layl", englishName: "The Night", verseCount: 21),
        QuranChapter(number: 93, transliteratedName: "Ad-Duhaa", englishName: "The Morning Hours", verseCount: 11),
        QuranChapter(number: 94, transliteratedName: "Ash-Sharh", englishName: "The Relief", verseCount: 8),
        QuranChapter(number: 95, transliteratedName: "At-Tin", englishName: "The Fig", verseCount: 8),
        QuranChapter(number: 96, transliteratedName: "Al-'Alaq", englishName: "The Clot", verseCount: 19),
        QuranChapter(number: 97, transliteratedName: "Al-Qadr", englishName: "The Power", verseCount: 5),
        QuranChapter(number: 98, transliteratedName: "Al-Bayyinah", englishName: "The Clear Proof", verseCount: 8),
        QuranChapter(number: 99, transliteratedName: "Az-Zalzalah", englishName: "The Earthquake", verseCount: 8),
        QuranChapter(number: 100, transliteratedName: "Al-'Adiyat", englishName: "The Courser", verseCount: 11),
        QuranChapter(number: 101, transliteratedName: "Al-Qari'ah", englishName: "The Calamity", verseCount: 11),
        QuranChapter(number: 102, transliteratedName: "At-Takathur", englishName: "Rivalry in World Increase", verseCount: 8),
        QuranChapter(number: 103, transliteratedName: "Al-'Asr", englishName: "The Declining Day", verseCount: 3),
        QuranChapter(number: 104, transliteratedName: "Al-Humazah", englishName: "The Traducer", verseCount: 9),
        QuranChapter(number: 105, transliteratedName: "Al-Fil", englishName: "The Elephant", verseCount: 5),
        QuranChapter(number: 106, transliteratedName: "Quraysh", englishName: "Quraysh", verseCount: 4),
        QuranChapter(number: 107, transliteratedName: "Al-Ma'un", englishName: "Small Kindnesses", verseCount: 7),
        QuranChapter(number: 108, transliteratedName: "Al-Kawthar", englishName: "Abundance", verseCount: 3),
        QuranChapter(number: 109, transliteratedName: "Al-Kafirun", englishName: "The Disbelievers", verseCount: 6),
        QuranChapter(number: 110, transliteratedName: "An-Nasr", englishName: "Divine Support", verseCount: 3),
        QuranChapter(number: 111, transliteratedName: "Al-Masad", englishName: "The Palm Fiber", verseCount: 5),
        QuranChapter(number: 112, transliteratedName: "Al-Ikhlas", englishName: "Sincerity", verseCount: 4),
        QuranChapter(number: 113, transliteratedName: "Al-Falaq", englishName: "The Daybreak", verseCount: 5),
        QuranChapter(number: 114, transliteratedName: "An-Nas", englishName: "Mankind", verseCount: 6)
    ]
}
